name: my_portfolio
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.22.1
  jaspr_flutter_embed: ^0.4.10
  jaspr_router: ^0.8.1
  google_fonts: ^6.2.1
  jaspr_material: ^0.2.2
  web_utils: ^1.0.19
  signals: ^6.3.0
  jaspr_riverpod: ^0.4.3
  

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  jaspr_builder: ^0.22.1

jaspr:
  mode: static
  flutter: embedded


flutter:
  uses-material-design: true
